name: Deploy Doos Admin Dashboard

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. Checkout repository
            - name: Checkout Code
              uses: actions/checkout@v3

            # 2. Setup Node.js
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            # 3. Install dependencies using NPM (NOT yarn)
            - name: Install Dependencies
              run: npm install

            # 4. Build Tailwind CSS
            - name: Build Tailwind CSS
              run: npm run build

            # 5. Debug files before uploading
            - name: Debug - List Files
              run: ls -lah && ls -R

            # 6. Upload files to VPS
            - name: Deploy to VPS
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: 67.223.117.9
                  username: root
                  key: |
                      -----BEGIN OPENSSH PRIVATE KEY-----
                      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
                      QyNTUxOQAAACA74wfcOjf97UHSY+GWiu2CerjL5ZIeu3HbHZ+bVmVG4AAAAJgaAGq6GgBq
                      ugAAAAtzc2gtZWQyNTUxOQAAACA74wfcOjf97UHSY+GWiu2CerjL5ZIeu3HbHZ+bVmVG4A
                      AAAEBwxFBRpbqBOOJ++q1ZMYmF+/1Puh/yZp4V/BauR8Vf2jvjB9w6N/3tQdJj4ZaK7YJ6
                      uMvlkh67cdsdn5tWZUbgAAAADmdpdGh1Yi1hY3Rpb25zAQIDBAUGBw==
                      -----END OPENSSH PRIVATE KEY-----
                  source: |
                      assets/**
                      renter/**
                      uber/**
                      index.html
                      .htaccess
                      favicon.png
                  target: /var/www/html/doosdoostest/admin

            # 7. Reload Apache after deploy
            - name: Reload Apache
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: 67.223.117.9
                  username: root
                  key: |
                      -----BEGIN OPENSSH PRIVATE KEY-----
                      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
                      QyNTUxOQAAACA74wfcOjf97UHSY+GWiu2CerjL5ZIeu3HbHZ+bVmVG4AAAAJgaAGq6GgBq
                      ugAAAAtzc2gtZWQyNTUxOQAAACA74wfcOjf97UHSY+GWiu2CerjL5ZIeu3HbHZ+bVmVG4A
                      AAAEBwxFBRpbqBOOJ++q1ZMYmF+/1Puh/yZp4V/BauR8Vf2jvjB9w6N/3tQdJj4ZaK7YJ6
                      uMvlkh67cdsdn5tWZUbgAAAADmdpdGh1Yi1hY3Rpb25zAQIDBAUGBw==
                      -----END OPENSSH PRIVATE KEY-----
                  script: |
                      cd /var/www/html/doosdoostest/admin
                      systemctl reload apache2
